### PR TITLE
picking latest version of dotnet-script when building. Fixing #213

### PR DESCRIPTION
**Pull request by andmos**

### CODE REVIEW

**Comment by filipw** [comment]
@andmos thanks, any idea why this failed on macOS?

**Comment by andmos** [comment]
Looking into it, worked locally on the macOS machines we have here...

**Comment by andmos** [comment]
Found it, 
```
{
  "message": "API rate limit exceeded for 52.3.55.28. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```
:( 
Makes sense, I would think Travis generates a lot of traffic without API tokens..

**Comment by andmos** [comment]
@seesharper is adding some tokens now, Let's see if that fixes the issue!

**Comment by seesharper** [comment]
@filip What if we simply create a dummy user on GitHub and create a personal access token for that user. That token can only be used to access repos belonging to the dummy user. This dummy user will not have any repos and the worst thing that could happen is that somebody steals the token and starts abusing the dummy user's account.

**Comment by andmos** [comment]
Yeah that should work. The only thing we are after here is the Github API...

**Comment by filipw** [comment]
sounds good to me

**Comment by andmos** [comment]
The token did the trick. As long as we just have the dummy-user I think we should be good.

**Comment by filipw** [comment]
thank you!

**Pull request merged**
