### PR TITLE
Simplify Dockerfile

### PR DESCRIPTION
**Pull request by GeorgeTsiokos**
- Use the public NuGet release via `dotnet tool install` 
- Use the Azure Container Registry .NET Core 2.1 SDK

### CODE REVIEW

**Comment by GeorgeTsiokos** [comment]
Also uses the newer Azure Container Registry .NET Core 2.1 SDK image URL

**Comment by filipw** [comment]
thanks a lot but I am not convinced about this change. It sort of changes the intent of this `Dockerfile`. it's supposed to contain the dotnet-script version built from the current source instead of the last published stable version.

**Comment by GeorgeTsiokos** [comment]
Personally I’m not a fan of supporting multiple build pipelines, but if that’s the purpose of this Dockerfile then definitely pass on this PR.

In any case please consider publishing an “official” docker image as part of your pipeline so people can discover this great project with a simple ‘docker run dotnet-script’ command from any platform

**Comment by seesharper** [comment]
@filipw Could you re-review 😀according to our internal discussion ?

**Pull request merged**
