### PR TITLE
Accept content-encoding of "gzip" for remote scripts

### PR DESCRIPTION
**Pull request by atifaziz**
This PR allows remote scripts to be served compressed. This can be handy for scripts that contain large amounts of static/literal embedded data that will compress well.

### CODE REVIEW

**Comment by atifaziz** [comment]
@seesharper, @filipw  LGTY?

**Comment by atifaziz** [comment]
Is there anything I am missing to get this reviewed and merged? I can understand lack of time spare time, but this PR proposes a minuscule change that I was hoping would be super quick to review.

**Comment by atifaziz** [comment]
👋

**Review by filipw — APPROVED** [review]
sorry I somehow missed it - thanks!

**Pull request merged**
