### PR TITLE
Add .csx extension to a new file if not specified

### PR DESCRIPTION
**Pull request by SlowLogicBoy**
This is pretty annoying -.-

### CODE REVIEW

**Comment by filipw** [comment]
thanks, can you add a test here https://github.com/filipw/dotnet-script/blob/master/src/Dotnet.Script.Tests/ScaffoldingTests.cs#L72 for this use case?

**Comment by SlowLogicBoy** [comment]
On the same test? shouldn't I create 2 new tests: one for `init` and one for `new`?

**Comment by SlowLogicBoy** [comment]
Right now I just added additional lines to existing tests, waiting for your response.

**Comment by filipw** [comment]
oops sorry for not being clear - it would make sense to have a different tests for this feature 😀
this way when they fail, it's explicit what has failed, instead of having to dig through asserts

**Comment by filipw** [comment]
thanks!

**Pull request merged**
