### PR TITLE
Updated McMaster.Extensions.CommandLineUtils to 3.0.0

### PR DESCRIPTION
**Pull request by badbort**
Updated the command line utils package.

I have done this as my .csx scripts pull a package that references a more recent version of McMaster.Extensions.CommandLineUtils. This causes the script to fail:

```
FileLoadException:Could not load file or assembly 'McMaster.Extensions.CommandLineUtils, Version=3.0.0.0, Culture=neutral, PublicKeyToken=6f71cb76b82f055d'. Could not find or load a specific file. (0x80131621)
at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, CancellationToken cancellationToken)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.Extensions.Hosting.HostBuilderExtensions.RunCommandLineApplicationAsync[TApp](IHostBuilder hostBuilder, String[] args, CancellationToken cancellationToken)
at Indi.UpdateIndex.WebJob.Program.Main(String[] args)
```

I have tried downgrading the referenced package to 2.2.5 but that version has some issues.

This does highlight an issue where dotnet-script dependencies conflict with the .csx nuget dependencies, however I figure this is a harmless upgrade that allows me to proceed in the short term

### CODE REVIEW

**Comment by filipw** [comment]
did you try running your script with `--isolated-load-context`?  e.g. `dotnet script main.csx --isolated-load-context`

**Review by filipw — APPROVED** [review]
LGTM thanks

**Comment by badbort** [comment]
Ah, I did not notice that option. I'll give that a shot

Cheers

**Comment by badbort** [comment]
Sorry not too familiar with completing PRs in github. Do I leave this in your hands now for merging?

**Review by filipw — APPROVED** [review]

**Review by seesharper — APPROVED** [review]

**Pull request merged**
