### PR TITLE
Remove dependency on System.Runtime.Loader.

### PR DESCRIPTION
**Pull request by SlowLogicBoy**
Fixes runtime error when running on net framework
Unable to load System.Runtime.Loader

I don't know if this has any side effects :?

### CODE REVIEW

**Comment by seesharper** [comment]
When you say "running on net framework" what does that mean exactly ? 
Do you put `#!  "net462"` or something similar at the beginning of the script?

**Comment by SlowLogicBoy** [comment]
No, I add dependency on Dotnet.Script.Core in my project (.csproj) that targets net461, and when I try running script it throws exception.

**Comment by seesharper** [comment]
I see. Just out of curiosity, what is the use case here?

**Comment by SlowLogicBoy** [comment]
I want to run some Wpf stuff, and it runs only with net framework :)
Basically trying to solve #44 at least partially.

**Comment by seesharper** [comment]
> Anyway that's not the only problem I have, trying to figure out other problems, like DependencyContext.Default == null for some reason

That is not going to be a simple thing to solve. We use something called a `DependencyContextReader` under the hood that parses the generated `project.assets.json` file and that does not work for full framework projects.

**Comment by filipw** [comment]
We can merge it - it's one dependency less, and while .NET Core doesn't support everything related to AppDomains (i.e. create new) this stuff here works just fine with .NET Core 2.0.

That said, as @seesharper mentioned, to target desktop .NET, a lot of other changes would be needed unfortunately.

**Comment by SlowLogicBoy** [comment]
Yea, after checking it out, it seems so.
For now I am able to run things I need on net core, I guess we'll see about the future :).

**Pull request merged**
