### PR TITLE
Fix parsing of #load to be case-sensitive

### PR DESCRIPTION
**Pull request by atifaziz**
The `#load` directive is case-sensitive in C# Interactive (`csi.exe`):

```
Microsoft (R) Visual C# Interactive Compiler version 2.9.0.63208
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
> #LOAD "foo.csx"
(1,2): error CS1024: Preprocessor directive expected
>
```

### CODE REVIEW

**Comment by atifaziz** [comment]
Not sure why the [`Dotnet.Script.Tests.ScaffoldingTests.ShouldRunCsxScriptDirectly` is failing](https://ci.appveyor.com/project/filipw/dotnet-script/build/1.0.792#L94). All tests are passing locally on my machine:

```
Test run for A:\dotnet-script\src\Dotnet.Script.Tests\bin\Debug\netcoreapp2.1\Dotnet.Script.Tests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 119. Passed: 119. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.2079 Minutes
```

🤔

**Comment by atifaziz** [comment]
Sorry for the follow-up commits. No more. I'm done. 😅

**Comment by seesharper** [comment]
@atifaziz That test is failing sporadically. Have to look into that

**Comment by atifaziz** [comment]
> That test is failing sporadically. Have to look into that

Noticed the same. Meanwhile, anything preventing from merging this PR?

**Comment by seesharper** [comment]
Thanks 👍

**Pull request merged**
